"""add Game table

Revision ID: 57c3fa60fdd8
Revises:
Create Date: 2026-01-13 00:07:37.458198

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "57c3fa60fdd8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column(
            "game_status",
            sa.Enum(
                "RELEASED",
                "ALPHA",
                "BETA",
                "EARLY_ACCESS",
                "OFFLINE",
                "CANCELLED",
                "RUMORED",
                "DELISTED",
                name="gamestatus",
            ),
            nullable=False,
        ),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("summary"),
        sa.UniqueConstraint("title"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("games")
    op.execute("DROP TYPE IF EXISTS gamestatus;")
    # ### end Alembic commands ###
